name: flutter_examples_sqlite_provider
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.2
  flutter_riverpod: ^2.5.1
  fpdart: ^1.1.0
  go_router: ^14.2.7
  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  sqlite_async: ^0.9.0
  sqlite3_flutter_libs: ^0.5.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#121212"